# Generated by Django 4.2 on 2023-04-05 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appartments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='price',
            field=models.PositiveIntegerField(verbose_name='цена'),
        ),
    ]
