# Generated by Django 4.2 on 2023-04-05 07:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appartments', '0002_alter_post_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('price', models.PositiveIntegerField(verbose_name='цена')),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='appartments')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='CLOSED', max_length=6)),
                ('address', models.CharField(max_length=200)),
                ('rooms', models.CharField(choices=[('NOT', 'Не указано'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('4+', '4+')], default='NOT', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Квартира',
                'verbose_name_plural': 'Квартиры',
                'ordering': ['created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
