# Generated by Django 4.2 on 2023-04-05 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appartments', '0004_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appartment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='appartments'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='sub_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appartments.comment'),
        ),
    ]
