# Generated by Django 4.2 on 2023-04-06 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appartments', '0007_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
