# Generated by Django 4.2 on 2023-04-08 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appartments', '0009_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='article',
            new_name='appartment',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='sub_comment',
        ),
    ]
