# Generated by Django 4.2 on 2023-04-08 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appartments', '0010_rename_article_comment_appartment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='appartment',
            new_name='article',
        ),
    ]
