# Generated by Django 4.2 on 2023-04-08 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appartments', '0011_rename_appartment_comment_article'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='article',
            new_name='appartment',
        ),
    ]
