# Generated by Django 4.2 on 2023-04-09 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appartments', '0013_favorites'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorites',
            options={'verbose_name': 'Избранное', 'verbose_name_plural': 'Избранные'},
        ),
    ]
